package expend_tracker.service;

import expend_tracker.model.Chain;
import expend_tracker.model.InvoiceFile;
import expend_tracker.model.Product;
import expend_tracker.model.Tag;
import expend_tracker.repositories.ChainRepository;
import expend_tracker.repositories.InvoiceFileRepository;
import expend_tracker.repositories.ProductRepository;
import expend_tracker.repositories.TagRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

/**
 * DataLoader class to load data into database
 */
@Component
public class DataLoader implements CommandLineRunner {

    @Autowired
    private ChainRepository chainRepository;
    @Autowired
    private TagRepository tagRepository;
    @Autowired
    private ProductRepository productRepository;
    @Autowired
    private InvoiceFileRepository invoiceFileRepository;

    @Override
    public void run(String... args) {

        if (chainRepository.count() == 0) {
            List<Chain> chain = Arrays.asList(
                    new Chain("Rewe"),
                    new Chain("Lidl"),
                    new Chain("Edeka"),
                    new Chain("Aldi Süd"),
                    new Chain("Aldi Nord"),
                    new Chain("Netto"),
                    new Chain("Penny"),
                    new Chain("Kaufland"),
                    new Chain("Real"),
                    new Chain("dm"),
                    new Chain("Rossmann"),
                    new Chain("Müller"),
                    new Chain("Budni"),
                    new Chain("Marktkauf"),
                    new Chain("Nah & Gut"),
                    new Chain("E-Center"),
                    new Chain("E aktiv Markt"),
                    new Chain("Nahkauf"),
                    new Chain("Norma")
            );

            chainRepository.saveAll(chain);
        }
        if (tagRepository.count() == 0) {
            List<Tag> tags = Arrays.asList(
                    new Tag("Milcherzeugnisse"),
                    new Tag("Fette und Öle"),
                    new Tag("Speiseeis"),
                    new Tag("Obst"),
                    new Tag("Gemüse"),
                    new Tag("Süßwaren"),
                    new Tag("Getreideerzeugnisse"),
                    new Tag("Backwaren"),
                    new Tag("Fleisch"),
                    new Tag("Fisch"),
                    new Tag("Eier"),
                    new Tag("Zuckerarten, Sirupe und Honig"),
                    new Tag("Gewürze"),
                    new Tag("Suppen und Soßen"),
                    new Tag("Säuglingsnahrung"),
                    new Tag("Wasser"),
                    new Tag("Kaffee"),
                    new Tag("Fruchtsäfte"),
                    new Tag("Erfrischungsgetränke und Limonaden"),
                    new Tag("Tee"),
                    new Tag("Alkoholhaltige Getränke"),
                    new Tag("Knabbereien"),
                    new Tag("Nüsse"),
                    new Tag("Sonstiges"),
                    new Tag("vararbeitete Lebensmittel"),
                    new Tag("Hygieneprodukte"),
                    new Tag("Unkategorisiert"),
                    new Tag("Nicht auslesbar")

            );

            tagRepository.saveAll(tags);
        }
        if (productRepository.count() == 0) {
            List<Product> product = Arrays.asList(
                    // #1 Milcherzeugnisse
                    new Product("Milch", tagRepository.findTagById(1L)),
                    new Product("Joghurt", tagRepository.findTagById(1L)),
                    new Product("Quark", tagRepository.findTagById(1L)),
                    new Product("Sahne", tagRepository.findTagById(1L)),
                    new Product("Butter", tagRepository.findTagById(1L)),
                    new Product("Frischkäse", tagRepository.findTagById(1L)),
                    new Product("Schmand", tagRepository.findTagById(1L)),
                    new Product("Molke", tagRepository.findTagById(1L)),
                    new Product("Buttermilch", tagRepository.findTagById(1L)),
                    new Product("Kefir", tagRepository.findTagById(1L)),
                    new Product("Ricotta", tagRepository.findTagById(1L)),
                    new Product("Mascarpone", tagRepository.findTagById(1L)),
                    new Product("Milchpulver", tagRepository.findTagById(1L)),
                    new Product("Ziegenkäse", tagRepository.findTagById(1L)),
                    new Product("Schlagsahne", tagRepository.findTagById(1L)),
                    new Product("Kondensmilch", tagRepository.findTagById(1L)),
                    new Product("Joghurtgetränk", tagRepository.findTagById(1L)),
                    new Product("Kakaogetränk", tagRepository.findTagById(1L)),
                    new Product("Mozzarella", tagRepository.findTagById(1L)),
                    new Product("Grana Padano", tagRepository.findTagById(1L)),
                    new Product("Skyr", tagRepository.findTagById(1L)),
                    new Product("Feta", tagRepository.findTagById(1L)),
                    new Product("Parmesan", tagRepository.findTagById(1L)),
                    new Product("Gouda", tagRepository.findTagById(1L)),
                    new Product("Emmentaler", tagRepository.findTagById(1L)),
                    new Product("Hirtenkäse", tagRepository.findTagById(1L)),
                    new Product("Bergkäse", tagRepository.findTagById(1L)),
                    new Product("Crème Fraîche", tagRepository.findTagById(1L)),


                    // #2 Fette und Öle
                    new Product("Olivenöl", tagRepository.findTagById(2L)),
                    new Product("Sonnenblumenöl", tagRepository.findTagById(2L)),
                    new Product("Kokosöl", tagRepository.findTagById(2L)),
                    new Product("Rapsöl", tagRepository.findTagById(2L)),
                    new Product("Erdnussöl", tagRepository.findTagById(2L)),
                    new Product("Sesamöl", tagRepository.findTagById(2L)),
                    new Product("Leinöl", tagRepository.findTagById(2L)),
                    new Product("Palmöl", tagRepository.findTagById(2L)),
                    new Product("Sojaöl", tagRepository.findTagById(2L)),
                    new Product("Butterschmalz", tagRepository.findTagById(2L)),
                    new Product("Schweineschmalz", tagRepository.findTagById(2L)),
                    new Product("Margarine", tagRepository.findTagById(2L)),
                    new Product("Ghee", tagRepository.findTagById(2L)),
                    new Product("Traubenkernöl", tagRepository.findTagById(2L)),
                    new Product("Walnussöl", tagRepository.findTagById(2L)),
                    new Product("Keimöl", tagRepository.findTagById(2L)),

                    // #3 Speiseeis
                    new Product("Vanilleeis", tagRepository.findTagById(3L)),
                    new Product("Schokoladeneis", tagRepository.findTagById(3L)),
                    new Product("Erdbeereis", tagRepository.findTagById(3L)),
                    new Product("Haselnusseis", tagRepository.findTagById(3L)),
                    new Product("Mango-Sorbet", tagRepository.findTagById(3L)),
                    new Product("Zitronensorbet", tagRepository.findTagById(3L)),
                    new Product("Pistazieneis", tagRepository.findTagById(3L)),
                    new Product("Stracciatella", tagRepository.findTagById(3L)),
                    new Product("Cookies-Cream", tagRepository.findTagById(3L)),
                    new Product("Bananeneis", tagRepository.findTagById(3L)),
                    new Product("Karamel-Eis", tagRepository.findTagById(3L)),
                    new Product("Joghurteis", tagRepository.findTagById(3L)),
                    new Product("Waldfruchteis", tagRepository.findTagById(3L)),
                    new Product("Milcheis", tagRepository.findTagById(3L)),
                    new Product("Kaffeeeis", tagRepository.findTagById(3L)),

                    // #4 Obst
                    new Product("Apfel", tagRepository.findTagById(4L)),
                    new Product("Banane", tagRepository.findTagById(4L)),
                    new Product("Orange", tagRepository.findTagById(4L)),
                    new Product("Erdbeere", tagRepository.findTagById(4L)),
                    new Product("Himbeere", tagRepository.findTagById(4L)),
                    new Product("Blaubeere", tagRepository.findTagById(4L)),
                    new Product("Kirsche", tagRepository.findTagById(4L)),
                    new Product("Traube", tagRepository.findTagById(4L)),
                    new Product("Melone", tagRepository.findTagById(4L)),
                    new Product("Kiwi", tagRepository.findTagById(4L)),
                    new Product("Ananas", tagRepository.findTagById(4L)),
                    new Product("Mango", tagRepository.findTagById(4L)),
                    new Product("Pfirsich", tagRepository.findTagById(4L)),
                    new Product("Pflaume", tagRepository.findTagById(4L)),
                    new Product("Birne", tagRepository.findTagById(4L)),
                    new Product("Wassermelone", tagRepository.findTagById(4L)),
                    new Product("Zitrone", tagRepository.findTagById(4L)),
                    new Product("Limette", tagRepository.findTagById(4L)),
                    new Product("Granatapfel", tagRepository.findTagById(4L)),
                    new Product("Avocado", tagRepository.findTagById(4L)),

                    // #5 Gemüse
                    new Product("Tomate", tagRepository.findTagById(5L)),
                    new Product("Gurke", tagRepository.findTagById(5L)),
                    new Product("Kartoffel", tagRepository.findTagById(5L)),
                    new Product("Möhre", tagRepository.findTagById(5L)),
                    new Product("Zwiebel", tagRepository.findTagById(5L)),
                    new Product("Paprika", tagRepository.findTagById(5L)),
                    new Product("Brokkoli", tagRepository.findTagById(5L)),
                    new Product("Spinat", tagRepository.findTagById(5L)),
                    new Product("Blumenkohl", tagRepository.findTagById(5L)),
                    new Product("Aubergine", tagRepository.findTagById(5L)),
                    new Product("Hokkaido", tagRepository.findTagById(5L)),
                    new Product("Süßkartoffel", tagRepository.findTagById(5L)),
                    new Product("Kohlrabi", tagRepository.findTagById(5L)),
                    new Product("Rote Beete", tagRepository.findTagById(5L)),
                    new Product("Zucchini", tagRepository.findTagById(5L)),
                    new Product("Champignon", tagRepository.findTagById(5L)),
                    new Product("Lauch", tagRepository.findTagById(5L)),
                    new Product("Spargel", tagRepository.findTagById(5L)),
                    new Product("Rosenkohl", tagRepository.findTagById(5L)),
                    new Product("Fenchel", tagRepository.findTagById(5L)),
                    new Product("Mais", tagRepository.findTagById(5L)),
                    new Product("Radieschen", tagRepository.findTagById(5L)),
                    new Product("Rettich", tagRepository.findTagById(5L)),
                    new Product("Ingwer", tagRepository.findTagById(5L)),
                    new Product("Knoblauch", tagRepository.findTagById(5L)),
                    new Product("Kürbis", tagRepository.findTagById(5L)),
                    new Product("Salat", tagRepository.findTagById(5L)),
                    new Product("Rucola", tagRepository.findTagById(5L)),
                    new Product("Kresse", tagRepository.findTagById(5L)),
                    new Product("Rahmspinat", tagRepository.findTagById(5L)),
                    new Product("Cherrytomaten", tagRepository.findTagById(5L)),
                    new Product("Rispentomaten", tagRepository.findTagById(5L)),
                    new Product("Fleischtomaten", tagRepository.findTagById(5L)),
                    new Product("Strauchtomaten", tagRepository.findTagById(5L)),
                    new Product("Cocktailtomaten", tagRepository.findTagById(5L)),
                    new Product("San Marzano Tomaten", tagRepository.findTagById(5L)),
                    new Product("Roma Tomaten", tagRepository.findTagById(5L)),
                    new Product("Heirloom Tomaten", tagRepository.findTagById(5L)),
                    new Product("Beefsteak Tomaten", tagRepository.findTagById(5L)),
                    new Product("Gelbe Tomaten", tagRepository.findTagById(5L)),
                    new Product("Grüne Tomaten", tagRepository.findTagById(5L)),
                    new Product("Schwarze Tomaten", tagRepository.findTagById(5L)),
                    new Product("Tiger Tomaten", tagRepository.findTagById(5L)),
                    new Product("Mini Romatomaten", tagRepository.findTagById(5L)),
                    new Product("Kumato", tagRepository.findTagById(5L)),
                    new Product("Brandywine Tomaten", tagRepository.findTagById(5L)),
                    new Product("Campari Tomaten", tagRepository.findTagById(5L)),
                    new Product("Herz Tomaten", tagRepository.findTagById(5L)),
                    new Product("Pear Tomaten", tagRepository.findTagById(5L)),
                    new Product("Plum Tomaten", tagRepository.findTagById(5L)),


                    // #6 Süßwaren
                    new Product("Schokolade", tagRepository.findTagById(6L)),
                    new Product("Bonbons", tagRepository.findTagById(6L)),
                    new Product("Kaugummi", tagRepository.findTagById(6L)),
                    new Product("Marshmallows", tagRepository.findTagById(6L)),
                    new Product("Gummibärchen", tagRepository.findTagById(6L)),

                    // #7 Getreideerzeugnisse
                    new Product("Haferflocken", tagRepository.findTagById(7L)),
                    new Product("Cornflakes", tagRepository.findTagById(7L)),
                    new Product("Couscous", tagRepository.findTagById(7L)),
                    new Product("Bulgur", tagRepository.findTagById(7L)),
                    new Product("Müsli", tagRepository.findTagById(7L)),
                    new Product("Penne", tagRepository.findTagById(7L)),
                    new Product("Spaghetti", tagRepository.findTagById(7L)),
                    new Product("Tagliatelle", tagRepository.findTagById(7L)),
                    new Product("Fusilli", tagRepository.findTagById(7L)),
                    new Product("Farfalle", tagRepository.findTagById(7L)),
                    new Product("Linguine", tagRepository.findTagById(7L)),
                    new Product("Fettuccine", tagRepository.findTagById(7L)),
                    new Product("Maccheroni", tagRepository.findTagById(7L)),
                    new Product("Cannelloni", tagRepository.findTagById(7L)),
                    new Product("Lasagne", tagRepository.findTagById(7L)),
                    new Product("Ravioli", tagRepository.findTagById(7L)),
                    new Product("Tortellini", tagRepository.findTagById(7L)),
                    new Product("Gnocchi", tagRepository.findTagById(7L)),
                    new Product("Pappardelle", tagRepository.findTagById(7L)),
                    new Product("Rotini", tagRepository.findTagById(7L)),
                    new Product("Orecchiette", tagRepository.findTagById(7L)),
                    new Product("Parboiled Reis", tagRepository.findTagById(7L)),
                    new Product("Basmati Reis", tagRepository.findTagById(7L)),
                    new Product("Weißer Reis", tagRepository.findTagById(7L)),
                    new Product("Brauner Reis", tagRepository.findTagById(7L)),
                    new Product("Jasmin Reis", tagRepository.findTagById(7L)),
                    new Product("Wildreis", tagRepository.findTagById(7L)),
                    new Product("Arborio Reis", tagRepository.findTagById(7L)),
                    new Product("Schwarzer Reis", tagRepository.findTagById(7L)),
                    new Product("Roter Reis", tagRepository.findTagById(7L)),
                    new Product("Klebreis", tagRepository.findTagById(7L)),
                    new Product("Langkornreis", tagRepository.findTagById(7L)),
                    new Product("Mittelkornreis", tagRepository.findTagById(7L)),
                    new Product("Kurzkornreis", tagRepository.findTagById(7L)),
                    new Product("Vollkornbasmati", tagRepository.findTagById(7L)),
                    new Product("Sushi-Reis", tagRepository.findTagById(7L)),
                    new Product("Carnaroli Reis", tagRepository.findTagById(7L)),
                    new Product("Reisnudeln", tagRepository.findTagById(7L)),
                    new Product("Reisflocken", tagRepository.findTagById(7L)),
                    new Product("Reismehl", tagRepository.findTagById(7L)),
                    new Product("Weizenmehl Typ 405", tagRepository.findTagById(7L)),
                    new Product("Weizenmehl Typ 550", tagRepository.findTagById(7L)),
                    new Product("Vollkornweizenmehl", tagRepository.findTagById(7L)),
                    new Product("Roggenmehl", tagRepository.findTagById(7L)),
                    new Product("Vollkornroggenmehl", tagRepository.findTagById(7L)),
                    new Product("Dinkelmehl", tagRepository.findTagById(7L)),
                    new Product("Vollkorndinkelmehl", tagRepository.findTagById(7L)),
                    new Product("Buchweizenmehl", tagRepository.findTagById(7L)),
                    new Product("Gerstenmehl", tagRepository.findTagById(7L)),
                    new Product("Hafermehl", tagRepository.findTagById(7L)),

                    // #8 Backwaren
                    new Product("Croissant", tagRepository.findTagById(8L)),
                    new Product("Donut", tagRepository.findTagById(8L)),
                    new Product("Baguette", tagRepository.findTagById(8L)),
                    new Product("Muffin", tagRepository.findTagById(8L)),
                    new Product("Pizzateig", tagRepository.findTagById(8L)),
                    new Product("Brot", tagRepository.findTagById(8L)),
                    new Product("Brötchen", tagRepository.findTagById(8L)),
                    new Product("Kräuterbaguette", tagRepository.findTagById(8L)),
                    new Product("Knobluachbaguette", tagRepository.findTagById(8L)),
                    new Product("Toastbrot", tagRepository.findTagById(8L)),
                    new Product("Pumpernickel", tagRepository.findTagById(8L)),
                    new Product("Knäckebrot", tagRepository.findTagById(8L)),
                    new Product("Vollkornbrot", tagRepository.findTagById(8L)),
                    new Product("Panettone", tagRepository.findTagById(8L)),
                    new Product("Ciabatta", tagRepository.findTagById(8L)),
                    new Product("Focaccia", tagRepository.findTagById(8L)),
                    new Product("Strudel", tagRepository.findTagById(8L)),
                    new Product("Scones", tagRepository.findTagById(8L)),
                    new Product("Brioche", tagRepository.findTagById(8L)),
                    new Product("Roggenbrot", tagRepository.findTagById(8L)),
                    new Product("Dinkelbrot", tagRepository.findTagById(8L)),
                    new Product("Zimtschnecke", tagRepository.findTagById(8L)),
                    new Product("Stollen", tagRepository.findTagById(8L)),
                    new Product("Challah", tagRepository.findTagById(8L)),
                    new Product("Naan-Brot", tagRepository.findTagById(8L)),
                    new Product("Bagels", tagRepository.findTagById(8L)),
                    new Product("Fladenbrot", tagRepository.findTagById(8L)),
                    new Product("Kaiserbrötchen", tagRepository.findTagById(8L)),
                    new Product("Schwarzbrot", tagRepository.findTagById(8L)),

                    // #9 Fleisch
                    new Product("Rindfleisch", tagRepository.findTagById(9L)),
                    new Product("Hähnchen", tagRepository.findTagById(9L)),
                    new Product("Schweinefleisch", tagRepository.findTagById(9L)),
                    new Product("Lammfleisch", tagRepository.findTagById(9L)),
                    new Product("Wurst", tagRepository.findTagById(9L)),
                    new Product("Speck", tagRepository.findTagById(9L)),
                    new Product("Hackfleisch", tagRepository.findTagById(9L)),
                    new Product("Salami", tagRepository.findTagById(9L)),
                    new Product("Schinken", tagRepository.findTagById(9L)),
                    new Product("Pute", tagRepository.findTagById(9L)),
                    new Product("Ente", tagRepository.findTagById(9L)),
                    new Product("Gans", tagRepository.findTagById(9L)),
                    new Product("Rinderhackleisch", tagRepository.findTagById(9L)),
                    new Product("Rinderfilet", tagRepository.findTagById(9L)),
                    new Product("Rinderbraten", tagRepository.findTagById(9L)),
                    new Product("Rindersteak", tagRepository.findTagById(9L)),
                    new Product("Schweinehackfleisch", tagRepository.findTagById(9L)),
                    new Product("Schweinefilet", tagRepository.findTagById(9L)),
                    new Product("Schweinebraten", tagRepository.findTagById(9L)),
                    new Product("Schweinesteak", tagRepository.findTagById(9L)),
                    new Product("Hähnchenbrust", tagRepository.findTagById(9L)),
                    new Product("Hähnchenkeule", tagRepository.findTagById(9L)),
                    new Product("Hähnchenflügel", tagRepository.findTagById(9L)),
                    new Product("Hähnchenbraten", tagRepository.findTagById(9L)),
                    new Product("Hähnchensteak", tagRepository.findTagById(9L)),
                    new Product("Hähnchenschenkel", tagRepository.findTagById(9L)),
                    new Product("Hähnchenleber", tagRepository.findTagById(9L)),

                    // #10 Fisch
                    new Product("Lachs", tagRepository.findTagById(10L)),
                    new Product("Forelle", tagRepository.findTagById(10L)),
                    new Product("Hering", tagRepository.findTagById(10L)),
                    new Product("Thunfisch", tagRepository.findTagById(10L)),
                    new Product("Kabeljau", tagRepository.findTagById(10L)),

                    // #11 Eier
                    new Product("Eier", tagRepository.findTagById(11L)),
                    new Product("Entenei", tagRepository.findTagById(11L)),
                    new Product("Gänseei", tagRepository.findTagById(11L)),
                    new Product("Wachtelei", tagRepository.findTagById(11L)),

                    // #12 Zuckerarten, Sirupe und Honig
                    new Product("Rohrzucker", tagRepository.findTagById(12L)),
                    new Product("Ahornsirup", tagRepository.findTagById(12L)),
                    new Product("Honig", tagRepository.findTagById(12L)),
                    new Product("Agavendicksaft", tagRepository.findTagById(12L)),
                    new Product("Brauner Zucker", tagRepository.findTagById(12L)),
                    new Product("Puderzucker", tagRepository.findTagById(12L)),
                    new Product("Kandiszucker", tagRepository.findTagById(12L)),
                    new Product("Kokosblütenzucker", tagRepository.findTagById(12L)),
                    new Product("Stevia", tagRepository.findTagById(12L)),
                    new Product("Xylit", tagRepository.findTagById(12L)),

                    // #13 Gewürze
                    new Product("Salz", tagRepository.findTagById(13L)),
                    new Product("Pfeffer", tagRepository.findTagById(13L)),
                    new Product("Curry", tagRepository.findTagById(13L)),
                    new Product("Paprikapulver", tagRepository.findTagById(13L)),
                    new Product("Chilipulver", tagRepository.findTagById(13L)),
                    new Product("Oregano", tagRepository.findTagById(13L)),
                    new Product("Basilikum", tagRepository.findTagById(13L)),
                    new Product("Rosmarin", tagRepository.findTagById(13L)),
                    new Product("Thymian", tagRepository.findTagById(13L)),
                    new Product("Majoran", tagRepository.findTagById(13L)),
                    new Product("Koriander", tagRepository.findTagById(13L)),
                    new Product("Kreuzkümmel", tagRepository.findTagById(13L)),

                    // #14 Suppen und Soßen
                    new Product("Tomatensuppe", tagRepository.findTagById(14L)),
                    new Product("Hühnersuppe", tagRepository.findTagById(14L)),
                    new Product("Rinderbrühe", tagRepository.findTagById(14L)),
                    new Product("Ketchup", tagRepository.findTagById(14L)),
                    new Product("Senf", tagRepository.findTagById(14L)),
                    new Product("Mayonnaise", tagRepository.findTagById(14L)),
                    new Product("Sojasoße", tagRepository.findTagById(14L)),
                    new Product("Barbecuesoße", tagRepository.findTagById(14L)),
                    new Product("Salsa", tagRepository.findTagById(14L)),
                    new Product("Pesto", tagRepository.findTagById(14L)),

                    // #16 Wasser
                    new Product("Stilles Wasser", tagRepository.findTagById(16L)),
                    new Product("Mineralwasser", tagRepository.findTagById(16L)),
                    new Product("Heilwasser", tagRepository.findTagById(16L)),

                    // #17 Kaffee
                    new Product("Filterkaffee", tagRepository.findTagById(17L)),
                    new Product("Espresso", tagRepository.findTagById(17L)),
                    new Product("Cappuccino", tagRepository.findTagById(17L)),
                    new Product("Latte Macchiato", tagRepository.findTagById(17L)),
                    new Product("Kaffeebohnen", tagRepository.findTagById(17L)),

                    // #18 Fruchtsäfte
                    new Product("Apfelsaft", tagRepository.findTagById(18L)),
                    new Product("Orangensaft", tagRepository.findTagById(18L)),
                    new Product("Traubensaft", tagRepository.findTagById(18L)),
                    new Product("Kirschsaft", tagRepository.findTagById(18L)),
                    new Product("Mangosaft", tagRepository.findTagById(18L)),
                    new Product("Grapefruitsaft", tagRepository.findTagById(18L)),
                    new Product("Ananassaft", tagRepository.findTagById(18L)),
                    new Product("Bananensaft", tagRepository.findTagById(18L)),
                    new Product("Multivitaminsaft", tagRepository.findTagById(18L)),
                    new Product("Granatapfelsaft", tagRepository.findTagById(18L)),
                    new Product("Zitronensaft", tagRepository.findTagById(18L)),

                    // #19 Erfrischungsgetränke und Limonaden
                    new Product("Cola", tagRepository.findTagById(19L)),
                    new Product("Limonade", tagRepository.findTagById(19L)),
                    new Product("Eistee", tagRepository.findTagById(19L)),
                    new Product("Energy Drink", tagRepository.findTagById(19L)),
                    new Product("Fruchtschorle", tagRepository.findTagById(19L)),
                    new Product("Bitter Lemon", tagRepository.findTagById(19L)),
                    new Product("Ginger Ale", tagRepository.findTagById(19L)),
                    new Product("Tonic Water", tagRepository.findTagById(19L)),
                    new Product("Wild Berry", tagRepository.findTagById(19L)),

                    // #20 Tee
                    new Product("Schwarz Tee", tagRepository.findTagById(20L)),
                    new Product("Grün Tee", tagRepository.findTagById(20L)),
                    new Product("Kräuter Tee", tagRepository.findTagById(20L)),
                    new Product("Früchte Tee", tagRepository.findTagById(20L)),
                    new Product("Roibusch Tee", tagRepository.findTagById(20L)),
                    new Product("Weißer Tee", tagRepository.findTagById(20L)),
                    new Product("Oolong Tee", tagRepository.findTagById(20L)),
                    new Product("Mate Tee", tagRepository.findTagById(20L)),
                    new Product("Chai Tee", tagRepository.findTagById(20L)),
                    new Product("Darjeeling Tee", tagRepository.findTagById(20L)),
                    new Product("Assam Tee", tagRepository.findTagById(20L)),
                    new Product("Earl Grey Tee", tagRepository.findTagById(20L)),
                    new Product("Jasmin Tee", tagRepository.findTagById(20L)),
                    new Product("Pfefferminz Tee", tagRepository.findTagById(20L)),
                    new Product("Kamillen Tee", tagRepository.findTagById(20L)),
                    new Product("Baldrian Tee", tagRepository.findTagById(20L)),
                    new Product("Lemongras Tee", tagRepository.findTagById(20L)),
                    new Product("Hibiskus Tee", tagRepository.findTagById(20L)),
                    new Product("Ingwer Tee", tagRepository.findTagById(20L)),
                    new Product("Matcha Tee", tagRepository.findTagById(20L)),
                    new Product("Pu-Erh Tee", tagRepository.findTagById(20L)),
                    new Product("Lapsang Souchong Tee", tagRepository.findTagById(20L)),
                    new Product("Yerba Mate Tee", tagRepository.findTagById(20L)),

                    // #21 Alkoholhaltige Getränke
                    new Product("Bier", tagRepository.findTagById(21L)),
                    new Product("Wein", tagRepository.findTagById(21L)),
                    new Product("Whisky", tagRepository.findTagById(21L)),
                    new Product("Wodka", tagRepository.findTagById(21L)),
                    new Product("Rum", tagRepository.findTagById(21L)),
                    new Product("Rotwein", tagRepository.findTagById(21L)),
                    new Product("Weißwein", tagRepository.findTagById(21L)),
                    new Product("Roséwein", tagRepository.findTagById(21L)),
                    new Product("Sekt", tagRepository.findTagById(21L)),
                    new Product("Champagner", tagRepository.findTagById(21L)),
                    new Product("Prosecco", tagRepository.findTagById(21L)),
                    new Product("Portwein", tagRepository.findTagById(21L)),
                    new Product("Sherry", tagRepository.findTagById(21L)),
                    new Product("Madeira", tagRepository.findTagById(21L)),
                    new Product("Marsala", tagRepository.findTagById(21L)),
                    new Product("Chianti", tagRepository.findTagById(21L)),
                    new Product("Bordeaux", tagRepository.findTagById(21L)),
                    new Product("Riesling", tagRepository.findTagById(21L)),
                    new Product("Sauvignon Blanc", tagRepository.findTagById(21L)),
                    new Product("Chardonnay", tagRepository.findTagById(21L)),
                    new Product("Pinot Noir", tagRepository.findTagById(21L)),
                    new Product("Merlot", tagRepository.findTagById(21L)),
                    new Product("Cabernet Sauvignon", tagRepository.findTagById(21L)),
                    new Product("Malbec", tagRepository.findTagById(21L)),
                    new Product("Zinfandel", tagRepository.findTagById(21L)),
                    new Product("Syrah/Shiraz", tagRepository.findTagById(21L)),
                    new Product("Gewürztraminer", tagRepository.findTagById(21L)),

                    // #22 Knabbereien
                    new Product("Chips", tagRepository.findTagById(22L)),
                    new Product("Popcorn", tagRepository.findTagById(22L)),
                    new Product("Cracker", tagRepository.findTagById(22L)),
                    new Product("Reiswaffeln", tagRepository.findTagById(22L)),
                    new Product("Salzstangen", tagRepository.findTagById(22L)),
                    new Product("Erdnussflips", tagRepository.findTagById(22L)),
                    new Product("Salzbrezeln", tagRepository.findTagById(22L)),
                    new Product("Pringles", tagRepository.findTagById(22L)),
                    new Product("Nachos", tagRepository.findTagById(22L)),
                    new Product("Tortilla Chips", tagRepository.findTagById(22L)),
                    new Product("Käsegebäck", tagRepository.findTagById(22L)),
                    new Product("Studentenfutter", tagRepository.findTagById(22L)),
                    new Product("Wasabi-Erbsen", tagRepository.findTagById(22L)),
                    new Product("Schokoladen-Rosinen", tagRepository.findTagById(22L)),
                    new Product("Gemüsechips", tagRepository.findTagById(22L)),
                    new Product("Mandelstifte", tagRepository.findTagById(22L)),
                    new Product("Sesamstangen", tagRepository.findTagById(22L)),
                    new Product("Maisstangen", tagRepository.findTagById(22L)),
                    new Product("Käsekräcker", tagRepository.findTagById(22L)),
                    new Product("Obstchips", tagRepository.findTagById(22L)),
                    new Product("Sojachips", tagRepository.findTagById(22L)),
                    new Product("Reiscracker", tagRepository.findTagById(22L)),
                    new Product("Brezenstücke", tagRepository.findTagById(22L)),


                    // #23 Nüsse
                    new Product("Walnüsse", tagRepository.findTagById(23L)),
                    new Product("Haselnüsse", tagRepository.findTagById(23L)),
                    new Product("Erdnüsse", tagRepository.findTagById(23L)),
                    new Product("Mandeln", tagRepository.findTagById(23L)),
                    new Product("Cashewnüsse", tagRepository.findTagById(23L)),
                    new Product("Pistazien", tagRepository.findTagById(23L)),
                    new Product("Macadamianüsse", tagRepository.findTagById(23L)),
                    new Product("Pekannüsse", tagRepository.findTagById(23L)),
                    new Product("Paranüsse", tagRepository.findTagById(23L)),

                    // #24 Sonstiges
                    new Product("Tofu", tagRepository.findTagById(24L)),
                    new Product("Seitan", tagRepository.findTagById(24L)),
                    new Product("Proteinriegel", tagRepository.findTagById(24L)),
                    new Product("Energieriegel", tagRepository.findTagById(24L)),
                    new Product("Veganes Fleisch", tagRepository.findTagById(24L)),
                    new Product("Backulver", tagRepository.findTagById(24L)),

                    // #25 verarbeitete Lebensmittel
                    new Product("Ajvar", tagRepository.findTagById(25L)),
                    new Product("Gehakte Tomaten", tagRepository.findTagById(25L)),
                    new Product("Tomatenmark", tagRepository.findTagById(25L)),

                    // #26 Hygieneprodukte
                    new Product("Taschentücher", tagRepository.findTagById(26L)),
                    new Product("Feuchttücher", tagRepository.findTagById(26L)),
                    new Product("Handseife", tagRepository.findTagById(26L)),
                    new Product("Desinfektionsmittel", tagRepository.findTagById(26L)),
                    new Product("Toilettenpapier", tagRepository.findTagById(26L)),
                    new Product("Zahnpasta", tagRepository.findTagById(26L)),
                    new Product("Shampoo", tagRepository.findTagById(26L)),
                    new Product("Duschgel", tagRepository.findTagById(26L)),
                    new Product("Mundspülung", tagRepository.findTagById(26L)),
                    new Product("Deodorant", tagRepository.findTagById(26L)),
                    new Product("Körpercreme", tagRepository.findTagById(26L)),
                    new Product("Handcreme", tagRepository.findTagById(26L)),
                    new Product("Gesichtscreme", tagRepository.findTagById(26L)),
                    new Product("Abschminktücher", tagRepository.findTagById(26L)),
                    new Product("Rasierklingen", tagRepository.findTagById(26L)),
                    new Product("Rasierschaum", tagRepository.findTagById(26L)),
                    new Product("Zahnseide", tagRepository.findTagById(26L)),
                    new Product("Zahnbürste", tagRepository.findTagById(26L)),
                    new Product("Nagelschere", tagRepository.findTagById(26L)),
                    new Product("Fußcreme", tagRepository.findTagById(26L)),
                    new Product("Seife", tagRepository.findTagById(26L)),
                    new Product("Damenbinden", tagRepository.findTagById(26L)),
                    new Product("Tampons", tagRepository.findTagById(26L)),
                    new Product("Inkontinenzeinlagen", tagRepository.findTagById(26L)),
                    new Product("Wattestäbchen", tagRepository.findTagById(26L)),
                    new Product("Wattepads", tagRepository.findTagById(26L)),
                    new Product("Kondome", tagRepository.findTagById(26L)),
                    new Product("Schwangerschaftstest", tagRepository.findTagById(26L)),
                    new Product("Desinfektionstücher", tagRepository.findTagById(26L)),

                    // #28 Nicht Auslesbar
                    new Product("Der Gerät", tagRepository.findTagById(28L))

            );

            productRepository.saveAll(product);
        }
    }
}
